In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


# Introduction to Tensors

## Creating Tensors

In [5]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [6]:
scaler.ndim # ndim represents number of dimensions (axes) of the ndarray

0

In [7]:
# Get tensor back as Python int
scaler.item()

7

In [8]:
# Vector
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [13]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([3])

In [14]:
# Matrix
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [15]:
matrix.ndim

2

In [16]:
matrix[0]

tensor([1, 2])

In [17]:
matrix.shape

torch.Size([2, 2])

In [18]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR[0][0][0]

tensor(1)