In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


# Introduction to Tensors

## Creating Tensors

In [5]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [6]:
scaler.ndim # ndim represents number of dimensions (axes) of the ndarray

0

In [7]:
# Get tensor back as Python int
scaler.item()

7

In [8]:
# Vector
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [13]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([3])

In [27]:
# Matrix
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [28]:
MATRIX.ndim

2

In [29]:
MATRIX[0]

tensor([1, 2])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR[0][0][0]

tensor(1)

### Random Tensors

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data

In [31]:
# Random tensors
randomTensor = torch.rand(3,4)
randomTensor

tensor([[0.9499, 0.3353, 0.3716, 0.9181],
        [0.2207, 0.0945, 0.1479, 0.4950],
        [0.6158, 0.4002, 0.0574, 0.4616]])

In [32]:
randomTensor.ndim

2

In [33]:
# Create a random tensor with similar shape to an image tensor
randomImageSizeTensor = torch.rand(size=(224,224,3)) # height, width, colour channels (R,G,B)
randomImageSizeTensor.shape, randomImageSizeTensor.ndim

(torch.Size([224, 224, 3]), 3)

In [35]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(4,5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

# Creating a range of tensors and tensors-like

In [39]:
# Use torch.arange()
oneToTen = torch.arange(0,11,1)
oneToTen

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
# creating tensors like
tenZeros = torch.zeros_like(input=oneToTen)
tenZeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and Deeplearning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [48]:
# Float 32 tensor
float32Tensor = torch.tensor([3.0, 4, 5.0], dtype=None, device=None, requires_grad=False) # device can be cpu/cuda, requires_grad is to track the gradients if needed
float32Tensor

tensor([3., 4., 5.])

In [49]:
float32Tensor.dtype

torch.float32

In [47]:
#change datatype of a tensor
float16Tensor = float32Tensor.type(torch.float16)
float16Tensor

tensor([3., 4., 5.], dtype=torch.float16)

# Manipulating tensors

1. Datatypes : To get datatype from tensor, can use `tensor.dtype`
2. Shape : To get datatype from tensor, can use `tensor.shape`
3. Device : To get device from tensor, can use `tensor.device`

In [3]:
# Find out details about tensor
someTensor = torch.rand(3,4)
print(someTensor)
print(f"Datatype of tensor : {someTensor.dtype}")
print(f"Shape of tensor : {someTensor.shape}")
print(f"Device of tensor : {someTensor.device}")

tensor([[0.6047, 0.9861, 0.0374, 0.9988],
        [0.6323, 0.4461, 0.4844, 0.6654],
        [0.6450, 0.9131, 0.9102, 0.7939]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor : cpu
